const SMALL_SCREEN_SIZE = 480;
const LARGE_SCREEN_SIZE = 1024;
const MIN_CARDS_QUANTITY = 5;
const MEDIUM_CARDS_QUANTITY = 8;
const MAX_CARDS_QUANTITY = 12;
const MIN_CARDS_ADDED = 4;
const MAX_CARDS_ADDED = 6;
const SHORT_MOVIES_DURATION = 40;

export {
  SMALL_SCREEN_SIZE,
  LARGE_SCREEN_SIZE,
  MIN_CARDS_QUANTITY,
  MEDIUM_CARDS_QUANTITY,
  MAX_CARDS_QUANTITY,
  MIN_CARDS_ADDED,
  MAX_CARDS_ADDED,
  SHORT_MOVIES_DURATION,
};
